taskapp/config/routes.rb
Rails.application.routes.draw do

  resources :projects
  root 'projects#index'

end

taskapp/app/models/project.rb
class Project < ActiveRecord::Base
  validates :title, presence: true
end

taskapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

taskapp/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else 
      render 'new'
    end
  end

  private
  
  def project_params
    params[:project].permit(:title)
  end
  
end

taskapp/app/helpers/application_helper.rb
module ApplicationHelper
end

taskapp/app/helpers/projects_helper.rb
module ProjectsHelper
end

taskapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taskapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= link_to "Home", "/" %>

</body>
</html>

taskapp/app/views/projects/index.html.erb
<h1>Projects</h1>

<ul>
  <% @projects.each do |project| %>
  <li><%= link_to project.title, project_path(project.id) %></li>
  <% end %>
</ul>

<p><%= link_to "Add New", new_project_path %></p>

taskapp/app/views/projects/new.html.erb
<h1>Add New</h1>

<%= form_for @project do |n| %>
<p>
  <%= n.label :title %><br>
  <%= n.text_field :title %>
  <% if @project.errors.any? %>
  <%= @project.errors.messages[:title][0] %>
  <% end %>
</p>

<p>
  <%= n.submit %>
</p>

<% end %>

taskapp/app/views/projects/show.html.erb
<h1><%= @project.title %></h1>